name: Nx Affected
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: git fetch --no-tags --prune --depth=1 origin main
      - run: npm ci
      - run: npx nx affected --base=origin/main --target=test --all
      - run: npx nx affected --base=origin/main --target=lint --all
      - run: npx nx affected --base=origin/main --target=build --all --prod
