name: Nx Concurrent jobs
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: git fetch --no-tags --prune --depth=1 origin main
      - run: npm ci
      - run: npx nx affected --base=origin/main --parallel --target=test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: git fetch --no-tags --prune --depth=1 origin main
      - run: npm ci
      - run: npx nx affected --base=origin/main --parallel --target=lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: git fetch --no-tags --prune --depth=1 origin main
      - run: npm ci
      - run: npx nx affected --base=origin/main --parallel --target=build --prod
