# https://medium.com/emoteev-blog/10x-faster-ci-with-nx-and-github-actions-9a51fc4e82a6
name: Nx Matrix
on: push
jobs:

  install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('package-lock.json') }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
        if: steps.cache.outputs.cache-hit != 'true'
      - run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'

  distributed-task:
    runs-on: ubuntu-latest
    needs: install-deps
    strategy:
      matrix:
        target: [ 'test', 'lint', 'build' ]
        jobIndex: [ 1, 2, 3, 4 ]
    env:
      jobCount: 4
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('package-lock.json') }}
      - run: node ./tools/run-many.js ${{ matrix.target }} ${{ matrix.jobIndex }} ${{ env.jobCount }} $GITHUB_REF
